/*
 * ai_infer.c - X-CUBE-AI network wrapper for st_yololcv1 192x192 INT8.
 * Not generated by CubeMX; safe across code regeneration.
 */
#include <string.h>

#include "ai_infer.h"
#include "main.h"

#include "network.h"
#include "network_data.h"

static ai_handle network = AI_HANDLE_NULL;

/* Activation arena (151.5 KiB) - lands in .bss -> RAM_D1 (AXI SRAM).
 * Input (108 KiB) and output (17 KiB) tensors live inside it
 * (generated with allocate-inputs/allocate-outputs). */
AI_ALIGNED(32)
static ai_u8 activations[AI_NETWORK_DATA_ACTIVATIONS_SIZE];

static ai_buffer *ai_input;
static ai_buffer *ai_output;

static void dwt_init(void)
{
  CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
  *(volatile uint32_t *)0xE0001FB0 = 0xC5ACCE55; /* DWT->LAR unlock (CM7) */
  DWT->CYCCNT = 0;
  DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

int ai_infer_init(void)
{
  /* The AI runtime refuses to initialize without the CRC peripheral clock. */
  __HAL_RCC_CRC_CLK_ENABLE();

  dwt_init();

  /* NOTE: weights stay in QSPI .rodata via the default binding (NULL).
   * Do NOT "shadow" them by memcpy from ai_network_data_weights_get();
   * that returns a descriptor TABLE, not the blob; binding a raw copy of it
   * silently runs the net on garbage weights (all-zero outputs). QSPI is
   * MPU-cacheable here, so there is no speed reason to move them anyway. */
  const ai_handle acts[] = { activations };
  ai_error err = ai_network_create_and_init(&network, acts, NULL);
  if (err.type != AI_ERROR_NONE)
    return -(int)err.code;

  ai_input = ai_network_inputs_get(network, NULL);
  ai_output = ai_network_outputs_get(network, NULL);
  if (ai_input == NULL || ai_output == NULL)
    return -1;

  return 0;
}

void ai_infer_fill_dummy_input(void)
{
  if (ai_input != NULL)
    memset(ai_input[0].data, 128, AI_NETWORK_IN_1_SIZE_BYTES);
}

/* One inference, returns raw DWT cycle count (0 on failure). */
static uint32_t ai_infer_run_cycles(void)
{
  if (network == AI_HANDLE_NULL)
    return 0;

  DWT->CYCCNT = 0;
  ai_i32 nbatch = ai_network_run(network, ai_input, ai_output);
  uint32_t cycles = DWT->CYCCNT;

  return (nbatch == 1) ? cycles : 0;
}

uint32_t ai_infer_run(void)
{
  uint32_t cycles = ai_infer_run_cycles();
  return cycles / (SystemCoreClock / 1000U);
}

uint32_t ai_infer_bench(uint32_t iters, uint32_t *cold_ms, uint32_t *warm_max_ms)
{
  uint32_t per_ms = SystemCoreClock / 1000U;
  uint32_t warm_min = 0xFFFFFFFFU, warm_max = 0;

  if (iters < 2)
    iters = 2;

  for (uint32_t i = 0; i < iters; i++)
  {
    uint32_t ms = ai_infer_run_cycles() / per_ms;
    if (i == 0)
    {
      if (cold_ms != NULL)
        *cold_ms = ms;               /* first run = cold I-cache */
    }
    else
    {
      if (ms < warm_min) warm_min = ms;
      if (ms > warm_max) warm_max = ms;
    }
  }

  if (warm_max_ms != NULL)
    *warm_max_ms = warm_max;
  return warm_min;                    /* best-case steady-state latency */
}

uint8_t *ai_infer_input_buffer(uint32_t *size_bytes)
{
  if (size_bytes != NULL)
    *size_bytes = AI_NETWORK_IN_1_SIZE_BYTES;
  return (ai_input != NULL) ? (uint8_t *)ai_input[0].data : NULL;
}

float *ai_infer_output_buffer(uint32_t *size_bytes)
{
  if (size_bytes != NULL)
    *size_bytes = AI_NETWORK_OUT_1_SIZE_BYTES;
  return (ai_output != NULL) ? (float *)ai_output[0].data : NULL;
}
